# Generated by Django 5.1.3 on 2024-12-31 19:02

"""
Migracion inicial de 
la aplicacion inventario
"""

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    """
    Clase encargada 
    de la migracion
    """

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Organizacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                                           primary_key=True,
                                           serialize=False,
                                           verbose_name='ID')),
                ('nombre_organizacion', models.CharField(max_length=100,
                                                         unique=True)),
            ],
            options={
                'verbose_name': 'Organización',
                'verbose_name_plural': 'Organizaciones',
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                                           primary_key=True,
                                           serialize=False,
                                           verbose_name='ID')),
                ('last_login', models.DateTimeField(blank=True,
                                                    null=True,
                                                    verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False,
                                                     help_text='Designates that this user has all permissions without explicitly assigning them.',
                                                     verbose_name='superuser status')),
                ('nombre', models.CharField(max_length=50)),
                ('correo_electronico', models.EmailField(max_length=50,
                                                         unique=True)),
                ('rol', models.CharField(choices=[('Usuario', 'Usuario'),
                                                  ('Administrador', 'Administrador')],
                                          default='Usuario',
                                          max_length=20)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('password', models.CharField(max_length=50)),
                ('groups', models.ManyToManyField(blank=True,
                                                  help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.',
                                                  related_name='user_set',
                                                  related_query_name='user',
                                                  to='auth.group',
                                                  verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True,
                                                            help_text='Specific permissions for this user.',
                                                            related_name='user_set', related_query_name='user',
                                                            to='auth.permission',
                                                            verbose_name='user permissions')),
                ('id_organizacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                                      to='inventario.organizacion')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                                           primary_key=True,
                                           serialize=False,
                                           verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('categoria', models.CharField(max_length=50)),
                ('cantidad', models.IntegerField()),
                ('precio_unidad', models.DecimalField(decimal_places=2,
                                                      max_digits=10)),
                ('stock_minimo', models.IntegerField()),
                ('id_organizacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                                      to='inventario.organizacion')),
            ],
        ),
        migrations.CreateModel(
            name='Movimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                                           primary_key=True,
                                           serialize=False,
                                           verbose_name='ID')),
                ('tipo_movimiento', models.CharField(choices=[('Salida', 'Salida'),
                                                              ('Entrada', 'Entrada')],
                                                     default='Salida',
                                                     max_length=20)),
                ('cantidad', models.IntegerField()),
                ('fecha', models.DateField(auto_now_add=True)),
                ('descripcion', models.CharField(max_length=300)),
                ('id_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                                 to=settings.AUTH_USER_MODEL)),
                ('id_producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                                  to='inventario.producto')),
            ],
        ),
    ]
