# Generated by Django 5.1.3 on 2024-12-31 19:03

"""
Segunda migracion
de la aplicacion inventarios
"""

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    """
    Clase encargada 
    de la migracion
    """

    dependencies = [
        ('inventario', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='id_organizacion',
            field=models.ForeignKey(null=True,
                                    on_delete=django.db.models.deletion.CASCADE,
                                    to='inventario.organizacion'),
        ),
    ]
