# Generated by Django 5.1.3 on 2025-01-31 06:02

"""
Cuarta migracion
de la aplicacion inventarios
"""

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    """
    Clase encargada 
    de la migracion
    """

    dependencies = [
        ('inventario', '0003_remove_movimiento_id_usuario_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Precios',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                                           primary_key=True,
                                           serialize=False,
                                           verbose_name='ID')),
                ('precio', models.DecimalField(decimal_places=2,
                                               max_digits=10)),
                ('fecha', models.DateField(auto_now_add=True)),
                ('id_producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                                  to='inventario.producto')),
            ],
        ),
    ]
