# Generated by Django 5.1.3 on 2025-03-05 09:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0005_rename_precio_unidad_producto_precio_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='id_organizacion',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, to='inventario.organizacion'),
            preserve_default=False,
        ),
    ]
